### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by aCampello** [aCampello/sponsors-search#1]
- [x] API to Get PDF
- [x] API to Parse PDF and put it in excel
- [x] Frontend with a search button
- [x] Configure PI to look for the page every week or so.
